### ISSUE TITLE
#32 Design a single question component

### ISSUE THREAD

**Issue by Bogdanpoda** [Bogdanpoda/SOEN341#25]
For epic story #32

- [ ] User Story: 
Each answered question within the forum page must include an upvote button (thumbs up), a downvote button (thumbs down) and an answer question.

Each question should be included within a component (object) that would receive as a parameter the asked question and is able to accept comments and display the number of upvotes etc...

- [ ] User Story Points: 50

- [ ] Acceptance test
- Users logged into the website can ask a question
- Regular users can not change the variables but can style view questions, answers, etc.

- [ ] Risk level: high

- [ ] Priority: medium

- [ ] User Story Tasks: 
- Thumbs Up / Thumbs Down
- Accepting comments on asked questions
- Display number of Upvotes / Downvotes

**Comment by nadiaaab** [comment]
each question able to accept comments, display the number of upvotes and downvotes
