### ISSUE TITLE
Sign-up page (front end)

### ISSUE THREAD

**Issue by Bogdanpoda** [Bogdanpoda/SOEN341#35]
- [ ] User Story:
Create a sign-up page where the user would have to put his information in order to sign up on the website and be able to ask questions.

- [ ] User story Points: 50

- [ ] Acceptance test:
- when making an account the password must match the confirmation password
- username must be available to use
- email must be available to use

- [ ] Risk level: high
If a user can not sign up in all other functionalities are interrupted.

- [ ] Priority: medium 

- [ ] User Story Tasks:
- Username
- name
- surname
- email
- password 2x times

**Comment by Pineapple920** [comment]
Finished demo sign up
